/**
 * Represents an HTTP service error from a backend call.
 */
export interface ServiceError {
  /**
   * HTTP error code.
   */
  code: number;
  /**
   * The error message generated by the backend.
   */
  message: string;
  /**
   * The HTTP path of the request.
   */
  path: string;
  /**
   * Used for the type guard.
   */
  type: "error";
}

/**
 * Type guard for a network call.
 */
export const isServiceError = <T>(
  response: T | ServiceError,
): response is ServiceError => {
  const isError = (response as ServiceError).type === "error";
  if (isError) {
    console.error(response);
  }

  return isError;
};
